# -*- coding: utf-8 -*-
"""AirVibe_Integration_Claim_AriVibes+Retrieve_Credentials.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WECQUrQFWH0JMfXJnKjDUx0KAsGnl75g

# 1. Sign Up For an Account @ [https://url.machinesaver.com/airvibe_activation](https://url.machinesaver.com/airvibe_activation)
# 2. Scan QR code to claim an AirVibe

# 3. Programmatically Retrieve LoRa Credentials
"""

import json
import requests

def get_auth_token(login: str, password: str) -> str:
  """Login to Machine Saver Activation API and retrieve access token."""
  url = "https://ap-api.wipom.net/api/auth/login"
  headers = {'Content-Type': 'application/json'}
  data = json.dumps({'login': login, 'password': password})

  response = requests.post(url, headers=headers, data=data)

  if response.status_code == 200:
    token_data = response.json()
    access_token = token_data['data']['accessToken']
    print(access_token)
    return access_token
  else:
    print(f"Failed to login: {response.status_code} - {response.text}")
    return None

access_token = get_auth_token(login="activation_portal_login", password="activation_portal_pass")

def get_with_EUI_AC(dev_eui: str, access_code: str, access_token: str) -> dict:
    """Get tags list for a specific device from Machine Saver API."""
    url = f"https://ap-api.wipom.net/api/devices/search?eui={dev_eui}&ac={access_code}"
    headers = {'Authorization': f'Bearer {access_token}'}

    response = requests.get(url, headers=headers)

    if response.status_code == 200:
        return response.json()
    else:
        print(f"Failed to fetch tag list: {response.status_code} - {response.text}")
        return None

get_with_EUI_AC(dev_eui="8C1F642113000017", access_code="74475383", access_token=access_token)

def get_with_serial(serial: str, access_token: str) -> dict:
    """Get data for a specific device from Machine Saver API."""
    url = f"https://ap-api.wipom.net/api/devices/serial?pattern={serial}"
    headers = {'Authorization': f'Bearer {access_token}'}

    response = requests.get(url, headers=headers)

    if response.status_code == 200:
        return response.json()
    else:
        print(f"Failed to fetch: {response.status_code} - {response.text}")
        return None

get_with_serial(serial="3000017", access_token=access_token)

"""# 4. Wake Up AirVibe
# 5. Decode Overall LoRa Packets
"""

